---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: old-pv-0
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  local:
    path: <PATH_ON_NODE>
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - <NODE_NAME>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: old-pvc-0
  namespace: minio-tmp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: old-pv-0
---